#服务端口
server:
  port: 9100
server.s
spring:
  application:
    #应用名称
    name: eshop-login
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  #数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/eshop
    type: com.alibaba.druid.pool.DruidDataSource
